#!/usr/bin/env python2

from handler import HandlerFinder
from download import Download
from pathlib2 import Path
import sys

if __name__ == "__main__":
    file_or_folder_path = Path(sys.argv[1])
    download = Download(file_or_folder_path)
    handler = HandlerFinder().find_handler(download)
    handler.handle(download)
